In [1]:
import numpy as np

# List

In [21]:
myList = ['one','two','three','four','five']

In [22]:
myList.remove('three')
myList

['one', 'two', 'four', 'five']

In [23]:
'four' in myList

True

In [24]:
myList.append('six')
len(myList)

5

In [25]:
for i in myList:
    print(i+': '+str(len(i)))

one: 3
two: 3
four: 4
five: 4
six: 3


In [26]:
myListLen = []
for i in myList:
    myListLen.append(len(str(i)))
myListLen

[3, 3, 4, 4, 3]

# Dictionary 

In [28]:
conv = {'apple':'Apfel', 'apples':'Äpfel','I':'Ich','and':'und','like': 'mag','strawberries':'Erdbeeren'}
conv

{'I': 'Ich',
 'and': 'und',
 'apple': 'Apfel',
 'apples': 'Äpfel',
 'like': 'mag',
 'strawberries': 'Erdbeeren'}

In [30]:
print(conv['apple'])
print(conv['like'])

Apfel
mag


In [31]:
var = "I like apples and strawberries"

In [33]:
varList = var.split(" ")
varList

['I', 'like', 'apples', 'and', 'strawberries']

In [35]:
for i in range(len(varList)):
    if( str(varList[i]) in conv):
        varList[i] = conv[varList[i]]
varList
        

['Ich', 'mag', 'Äpfel', 'und', 'Erdbeeren']

In [37]:
convVar = " ".join(varList)
convVar

'Ich mag Äpfel und Erdbeeren'

# Numpy arrays 

In [39]:
arr = np.zeros((8,8))
arr.dtype

dtype('float64')

In [44]:
count = 1
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        arr[i,j] = count
        count +=1
arr

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30., 31., 32.],
       [33., 34., 35., 36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45., 46., 47., 48.],
       [49., 50., 51., 52., 53., 54., 55., 56.],
       [57., 58., 59., 60., 61., 62., 63., 64.]])

In [46]:
print(arr.transpose())

[[ 1.  9. 17. 25. 33. 41. 49. 57.]
 [ 2. 10. 18. 26. 34. 42. 50. 58.]
 [ 3. 11. 19. 27. 35. 43. 51. 59.]
 [ 4. 12. 20. 28. 36. 44. 52. 60.]
 [ 5. 13. 21. 29. 37. 45. 53. 61.]
 [ 6. 14. 22. 30. 38. 46. 54. 62.]
 [ 7. 15. 23. 31. 39. 47. 55. 63.]
 [ 8. 16. 24. 32. 40. 48. 56. 64.]]


In [47]:
arr[0:4,0:4]

array([[ 1.,  2.,  3.,  4.],
       [ 9., 10., 11., 12.],
       [17., 18., 19., 20.],
       [25., 26., 27., 28.]])

In [50]:
arr1D = arr.flatten()
print(arr1D)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53. 54.
 55. 56. 57. 58. 59. 60. 61. 62. 63. 64.]


In [52]:
arr2D = arr1D.reshape(8,8)
print(arr2D)

[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30. 31. 32.]
 [33. 34. 35. 36. 37. 38. 39. 40.]
 [41. 42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55. 56.]
 [57. 58. 59. 60. 61. 62. 63. 64.]]


In [55]:
var = "how much wood would a woodchuck chuck if a woodchuck could chuck wood"
varList = var.split(" ")
varCount ={}
for i in range(len(varList)):
    if(varList[i] in varCount):
        varCount[varList[i]] = varCount[varList[i]]+1
    else:
        varCount.update({varList[i]:1})
    

In [56]:
varCount

{'a': 2,
 'chuck': 2,
 'could': 1,
 'how': 1,
 'if': 1,
 'much': 1,
 'wood': 2,
 'woodchuck': 2,
 'would': 1}

In [60]:
img = np.ones((4,4))
img

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
imgborder = np.zeros((img.shape[0]+2,img.shape[0]+2))
imgborder

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [66]:
for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        imgborder[i+1][j+1] = 1
imgborder

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#  Counting the frequency of words

In [71]:
def word_count(var):
    varList = var.split(" ")
    varCount ={}
    for i in range(len(varList)):
        if(varList[i] in varCount):
            varCount[varList[i]] = varCount[varList[i]]+1
        else:
            varCount.update({varList[i]:1})
    print(varCount)

# Adding pading to the image 

In [72]:
def add_border(img):
    imgborder = np.zeros((img.shape[0]+2,img.shape[0]+2))
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            imgborder[i+1][j+1] = 1
    print(imgborder)
    

In [73]:
var = "how much wood would a woodchuck chuck if a woodchuck could chuck wood"
word_count(var)

{'wood': 2, 'how': 1, 'woodchuck': 2, 'much': 1, 'would': 1, 'chuck': 2, 'if': 1, 'could': 1, 'a': 2}


In [74]:
img = np.ones((4,4))
add_border(img)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
